apiVersion: v1
kind: Service
metadata:
  name: seatbooking-webapp
  labels:
    app: seatbooking-app
    name: seatbooking-webapp
spec:
  selector:
    app: seatbooking-app
    name: seatbooking-web-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatbooking-webapp
  labels:
    app: seatbooking-app
    name: seatbooking-webapp
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: seatbooking-web-pod
  #replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: seatbooking-web-pod
      labels:
        app: seatbooking-app
        name: seatbooking-web-pod
    spec:
      containers:
        - name: seatbooking-web-container
          image: dhamodaran/seatbooking_app:latest
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 80
